### ISSUE TITLE
Signed acknowledgements not working

### ISSUE THREAD

**Issue by ronblom-rinis** [eluinstra/ebms-admin#8]
Hi,

I'm just testing with the ebms-admin-2.17.7 and getting positive results. Only when using CPA's with tns:ackSignatureRequested="always" are not working. When receiving an acknowledgement I see the following error:

`
2021-06-23 12:51:29,071 [qtp910091170-22] WARN  nl.clockwork.ebms.processor.AcknowledgmentProcessor - Unable to process Acknowledgment 20210623-115128-80263@127.0.0.1
nl.clockwork.ebms.validation.ValidationException: Certificate not found!
	at nl.clockwork.ebms.signing.EbMSSignatureValidator.validate(EbMSSignatureValidator.java:124) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.validation.SignatureValidator.validate(SignatureValidator.java:80) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.validation.EbMSMessageValidator.validateAcknowledgment(EbMSMessageValidator.java:92) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.AcknowledgmentProcessor.processAcknowledgment(AcknowledgmentProcessor.java:128) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor.processRequest(EbMSMessageProcessor.java:184) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor.processRequest(EbMSMessageProcessor.java:149) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor$$FastClassBySpringCGLIB$$101cfb36.invoke(<generated>) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor$$EnhancerBySpringCGLIB$$e05f4f57.processRequest(<generated>) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.EbMSInputStreamHandler.handleRequest(EbMSInputStreamHandler.java:103) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.EbMSInputStreamHandler.handle(EbMSInputStreamHandler.java:64) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.EbMSHttpHandler.handle(EbMSHttpHandler.java:103) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.servlet.EbMSServlet.service(EbMSServlet.java:55) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) ~[ebms-admin-2.17.7.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
2021-06-23 12:51:29,101 [qtp910091170-22] INFO  nl.clockwork.ebms.message - >>>>
StatusCode=204
`

Sending an acknowledgement drops the following error:

`
2021-06-23 13:42:03,324 [qtp782378927-37] ERROR nl.clockwork.ebms.server.EbMSInputStreamHandler -
nl.clockwork.ebms.processor.EbMSProcessingException: No signing certificate found for deliveryChannel "OVERHEID_DC_T_Besteffort_S_Transport_R_" in CPA "CPA_TEST_EBMS_ADAPTER_SIGN_ACK"
	at nl.clockwork.ebms.signing.EbMSSignatureGenerator.sign(EbMSSignatureGenerator.java:117) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.signing.EbMSSignatureGenerator.generate(EbMSSignatureGenerator.java:95) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.AcknowledgmentProcessor.processAcknowledgment(AcknowledgmentProcessor.java:84) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor.processMessage(EbMSMessageProcessor.java:280) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor.processRequest(EbMSMessageProcessor.java:168) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor.processRequest(EbMSMessageProcessor.java:149) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor$$FastClassBySpringCGLIB$$101cfb36.invoke(<generated>) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[ebms-admin-2.17.7.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.processor.EbMSMessageProcessor$$EnhancerBySpringCGLIB$$6457fa38.processRequest(<generated>) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.EbMSInputStreamHandler.handleRequest(EbMSInputStreamHandler.java:103) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.EbMSInputStreamHandler.handle(EbMSInputStreamHandler.java:64) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.EbMSHttpHandler.handle(EbMSHttpHandler.java:103) ~[ebms-admin-2.17.7.jar:?]
	at nl.clockwork.ebms.server.servlet.EbMSServlet.service(EbMSServlet.java:55) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) ~[ebms-admin-2.17.7.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) ~[ebms-admin-2.17.7.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
2021-06-23 13:42:03,325 [qtp782378927-37] INFO  nl.clockwork.ebms.message - >>>>
StatusCode=500
`

btw in my test environment the signing of messages is working.

**Comment by eluinstra** [comment]
hello,

sorry for the late response.

The errors are caused by missing signing certificates on the default DeliveryChannel in your CPA. I saw this issue a few times before lately.
You can fix this by adding the missing SenderBinding in the DocExchange of the default DeliveryChannel. See also this example https://github.com/eluinstra/ebms-admin/blob/ebms-admin-2.17.x/resources/CPAs/cpaStubEBF.rm.https.signed.ackSigned.xml.


kind regards,
Edwin
